# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AFDWin1.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from Graph import *

class UIAFDWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1002, 578)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralWidget)
        self.graphicsView.setGeometry(QtCore.QRect(216, 40, 771, 471))
        self.graphicsView.setObjectName("graphicsView")
        self.nodoBtn = QtWidgets.QPushButton(self.centralWidget)
        self.nodoBtn.setGeometry(QtCore.QRect(20, 40, 171, 32))
        self.nodoBtn.setObjectName("nodoBtn")
        self.aristaBtn = QtWidgets.QPushButton(self.centralWidget)
        self.aristaBtn.setGeometry(QtCore.QRect(20, 130, 171, 32))
        self.aristaBtn.setObjectName("aristaBtn")
        self.evaluarBtn = QtWidgets.QPushButton(self.centralWidget)
        self.evaluarBtn.setGeometry(QtCore.QRect(210, 6, 112, 32))
        self.evaluarBtn.setObjectName("evaluarBtn")
        self.inputTxt = QtWidgets.QLineEdit(self.centralWidget)
        self.inputTxt.setGeometry(QtCore.QRect(320, 10, 666, 21))
        self.inputTxt.setObjectName("inputTxt")
        self.TabInfo = QtWidgets.QTabWidget(self.centralWidget)
        self.TabInfo.setGeometry(QtCore.QRect(10, 240, 201, 271))
        self.TabInfo.setObjectName("TabInfo")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.borrarBtn1 = QtWidgets.QPushButton(self.tab)
        self.borrarBtn1.setGeometry(QtCore.QRect(40, 210, 112, 32))
        self.borrarBtn1.setObjectName("borrarBtn1")
        self.table1 = QtWidgets.QTableWidget(self.tab)
        self.table1.setGeometry(QtCore.QRect(10, 7, 174, 201))
        self.table1.setColumnCount(2)
        self.table1.setObjectName("table1")
        self.table1.setRowCount(0)
        self.table1.horizontalHeader().setCascadingSectionResizes(False)
        self.table1.horizontalHeader().setDefaultSectionSize(79)
        self.TabInfo.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.borrarBtn2 = QtWidgets.QPushButton(self.tab_2)
        self.borrarBtn2.setGeometry(QtCore.QRect(40, 230, 112, 32))
        self.borrarBtn2.setObjectName("borrarBtn2")
        self.table2 = QtWidgets.QTableWidget(self.tab_2)
        self.table2.setGeometry(QtCore.QRect(10, 7, 174, 221))
        self.table2.setColumnCount(1)
        self.table2.setObjectName("table2")
        self.table2.setRowCount(0)
        self.table2.horizontalHeader().setDefaultSectionSize(171)
        self.TabInfo.addTab(self.tab_2, "")
        self.inicioBtn = QtWidgets.QPushButton(self.centralWidget)
        self.inicioBtn.setGeometry(QtCore.QRect(20, 155, 171, 32))
        self.inicioBtn.setObjectName("inicioBtn")
        self.aceptaBtn = QtWidgets.QPushButton(self.centralWidget)
        self.aceptaBtn.setGeometry(QtCore.QRect(20, 180, 171, 32))
        self.aceptaBtn.setObjectName("aceptaBtn")
        self.condTxt = QtWidgets.QLineEdit(self.centralWidget)
        self.condTxt.setGeometry(QtCore.QRect(30, 100, 151, 21))
        self.condTxt.setObjectName("condTxt")
        self.actuBtn = QtWidgets.QPushButton(self.centralWidget)
        self.actuBtn.setGeometry(QtCore.QRect(0, 0, 112, 32))
        self.actuBtn.setObjectName("actuBtn")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(70, 80, 61, 16))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1002, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuArchivo = QtWidgets.QMenu(self.menuBar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuAcciones = QtWidgets.QMenu(self.menuBar)
        self.menuAcciones.setObjectName("menuAcciones")
        self.menuAlfabeto = QtWidgets.QMenu(self.menuAcciones)
        self.menuAlfabeto.setObjectName("menuAlfabeto")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionAbrir = QtWidgets.QAction(MainWindow)
        self.actionAbrir.setObjectName("actionAbrir")
        self.actionCargar = QtWidgets.QAction(MainWindow)
        self.actionCargar.setObjectName("actionCargar")
        self.actionNuevo = QtWidgets.QAction(MainWindow)
        self.actionNuevo.setObjectName("actionNuevo")
        self.actionGuardar = QtWidgets.QAction(MainWindow)
        self.actionGuardar.setObjectName("actionGuardar")
        self.actionGuardar_y_Salir = QtWidgets.QAction(MainWindow)
        self.actionGuardar_y_Salir.setObjectName("actionGuardar_y_Salir")
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.actionConvertir_a_AFN = QtWidgets.QAction(MainWindow)
        self.actionConvertir_a_AFN.setObjectName("actionConvertir_a_AFN")
        self.actionBinario = QtWidgets.QAction(MainWindow)
        self.actionBinario.setObjectName("actionBinario")
        self.actionNumerico = QtWidgets.QAction(MainWindow)
        self.actionNumerico.setObjectName("actionNumerico")
        self.actionCorreo = QtWidgets.QAction(MainWindow)
        self.actionCorreo.setObjectName("actionCorreo")
        self.actionAlfabetico = QtWidgets.QAction(MainWindow)
        self.actionAlfabetico.setObjectName("actionAlfabetico")
        self.actionAlfanumerico = QtWidgets.QAction(MainWindow)
        self.actionAlfanumerico.setObjectName("actionAlfanumerico")
        self.menuArchivo.addAction(self.actionNuevo)
        self.menuArchivo.addAction(self.actionAbrir)
        self.menuArchivo.addAction(self.actionCargar)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionGuardar)
        self.menuArchivo.addAction(self.actionGuardar_y_Salir)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionSalir)
        self.menuAlfabeto.addAction(self.actionAlfabetico)
        self.menuAlfabeto.addAction(self.actionAlfanumerico)
        self.menuAlfabeto.addAction(self.actionCorreo)
        self.menuAlfabeto.addAction(self.actionBinario)
        self.menuAlfabeto.addAction(self.actionNumerico)
        self.menuAcciones.addAction(self.menuAlfabeto.menuAction())
        self.menuAcciones.addAction(self.actionConvertir_a_AFN)
        self.menuBar.addAction(self.menuArchivo.menuAction())
        self.menuBar.addAction(self.menuAcciones.menuAction())
        self.menuBar.setNativeMenuBar(False)
        self.retranslateUi(MainWindow)
        self.TabInfo.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nodoBtn.setText(_translate("MainWindow", "Agregar Nodo"))
        self.aristaBtn.setText(_translate("MainWindow", "Agregar Arista"))
        self.evaluarBtn.setText(_translate("MainWindow", "Evaluar"))
        self.borrarBtn1.setText(_translate("MainWindow", "Borrar"))
        self.TabInfo.setTabText(self.TabInfo.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.borrarBtn2.setText(_translate("MainWindow", "Borrar"))
        self.TabInfo.setTabText(self.TabInfo.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.inicioBtn.setText(_translate("MainWindow", "Nodo Inicial"))
        self.aceptaBtn.setText(_translate("MainWindow", "Nodo Acepatacion"))
        self.actuBtn.setText(_translate("MainWindow", "Actualizar"))
        self.label.setText(_translate("MainWindow", "Condicion"))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))
        self.menuAcciones.setTitle(_translate("MainWindow", "Acciones"))
        self.menuAlfabeto.setTitle(_translate("MainWindow", "Alfabeto"))
        self.actionAbrir.setText(_translate("MainWindow", "Abrir"))
        self.actionCargar.setText(_translate("MainWindow", "Cargar"))
        self.actionNuevo.setText(_translate("MainWindow", "Nuevo"))
        self.actionGuardar.setText(_translate("MainWindow", "Guardar"))
        self.actionGuardar_y_Salir.setText(_translate("MainWindow", "Guardar y Salir"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
        self.actionConvertir_a_AFN.setText(_translate("MainWindow", "Convertir a AFN"))
        self.actionBinario.setText(_translate("MainWindow", "Binario"))
        self.actionNumerico.setText(_translate("MainWindow", "Numerico"))
        self.actionCorreo.setText(_translate("MainWindow", "Correo"))
        self.actionAlfabetico.setText(_translate("MainWindow", "Alfabetico"))
        self.actionAlfanumerico.setText(_translate("MainWindow", "Alfanumerico"))

